[package]
name = "willGuimont/dashy-dango"
version = "1.0.0"
description = "Help the Dango survive by fighting waves of enemies. Dash into enemies to eliminate them."
license = "ISC"
repository = "https://github.com/willGuimont/dashy-dango"

[dependencies]
"willGuimont/dashy-dango" = "1.0.0"

[[module]]
name = "dashy-dango"
source = "build/cart.wasm"
abi = "wasm4"

[module.interfaces]
wasm4 = "0.0.1"

[[command]]
name = "play"
module = "dashy-dango"
